trigger:
- main

resources:
- repo: self

variables: # <---------------------- AGREGA LAS VARIABLES
  - group: CICD
  - name: appVersion
    value: $[variables.appVersion]

parameters:
  - name: tag 
    default: '$(Build.BuildId)'
  - name: imageName
    default: 'demo-page'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool: local-agent

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        repository: ${{ parameters.imageName }}
        command: build
        dockerfile: '**/Dockerfile'
        tags: ${{ parameters.tag }}
        arguments: '--build-arg VERSION="$(appVersion)"'
        
    - task: Docker@2
      displayName: Push to ACR
      inputs:
        command: Push
        containerRegistry: registryConnection
        repository: ${{ parameters.imageName }}
        tags: ${{ parameters.tag }}